name: Deploy to AWS Devlopemnt Environment

on:
  push:
    branches:
      - Dev@1
  pull_request:
    branches:
      - Dev@1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to AWS
      uses: aws/login@v1
      with:
        creds: ${{ secrets.AWS_CREDENTIALS }}

    - name: Deploy to AWS
      run: |
        aws webapp up --name ${{ secrets.AWS_WEBAPP_NAME }} --location ${{ secrets.AWS_LOCATION }}
